-- Создаем таблицу.
-- Создаем числовой столбец счетчик, не пустой, уникальное значение.
-- Создаем текстовый столбец, обязательно для заполнения.
-- Создаем текстовый столбец, обязательно для заполнения.
-- Указываем где ключи.
-- Указываем где уникальное значение, зависит от всех перечисленных столбцов.


CREATE TABLE "USER" (
	USER_ID SERIAL NOT NULL UNIQUE,
	USER_N_ID VARCHAR (64) NOT NULL UNIQUE,
	USER_P_ID VARCHAR (64) NOT NULL UNIQUE,
	PRIMARY KEY (USER_ID, USER_N_ID, USER_P_ID)
);

CREATE TABLE "USER_NAME" (
	USER_N_ID VARCHAR (64) NOT NULL UNIQUE
	REFERENCES "USER" (USER_N_ID)
	ON DELETE CASCADE ON UPDATE CASCADE PRIMARY KEY,
	USER_N_name VARCHAR (64) NOT NULL UNIQUE,
	USER_N_Telegram VARCHAR (64) NULL
);

CREATE TABLE "USER_PRIVATE" (
	USER_P_ID VARCHAR (64) NOT NULL UNIQUE
	REFERENCES "USER" (USER_P_ID)
	ON DELETE CASCADE ON UPDATE CASCADE PRIMARY KEY,
	USER_P_email VARCHAR (64) NOT NULL UNIQUE,
	USER_P_password VARCHAR (64) NOT NULL
);

CREATE TABLE "SETTINGS" (
	USER_ID INT NOT NULL
	REFERENCES "USER" (USER_ID)
	ON DELETE CASCADE ON UPDATE CASCADE PRIMARY KEY,
	SET_theme TEXT NULL,
	SET_preferences TEXT NULL
);

CREATE TABLE "CATEGORY" (
	CAT_ID SERIAL NOT NULL UNIQUE,
	USER_ID INT NOT NULL
	REFERENCES "USER" (USER_ID)
	ON DELETE CASCADE ON UPDATE CASCADE,
	CAT_name VARCHAR (64) NOT NULL,
	PRIMARY KEY (USER_ID, CAT_name),
	UNIQUE (USER_ID, CAT_name)
);

CREATE TABLE "ACTIVITY_LIST" (
	ACTL_ID SERIAL NOT NULL UNIQUE,
	USER_ID INT NOT NULL,
	ACTL_name VARCHAR(64) NOT NULL,
	CAT_name VARCHAR(64) NOT NULL, 
	FOREIGN KEY (USER_ID, CAT_name)
	REFERENCES "CATEGORY" (USER_ID, CAT_name)
	ON DELETE CASCADE ON UPDATE CASCADE,
	PRIMARY KEY (USER_ID, ACTL_name, CAT_name),
	UNIQUE (USER_ID, ACTL_name, CAT_name)
);

CREATE TABLE "ACTIVITY" (
	ACT_ID SERIAL NOT NULL UNIQUE PRIMARY KEY,
	USER_ID INT NOT NULL,
	ACTL_name VARCHAR(64) NOT NULL,
	ACT_time INT NOT NULL,
	ACT_date DATE NOT NULL,
	CAT_name VARCHAR(64) NOT NULL,
	ACT_comment TEXT NULL,
	FOREIGN KEY (USER_ID, ACTL_name, CAT_name)
	REFERENCES "ACTIVITY_LIST" (USER_ID, ACTL_name, CAT_name)
	ON DELETE CASCADE ON UPDATE CASCADE
);