# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\add_event.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1440, 1080)
        Form.setStyleSheet("background-color:rgba(34,39,51,0.137);")
        self.a_widget_2 = QtWidgets.QWidget(Form)
        self.a_widget_2.setGeometry(QtCore.QRect(1080, 0, 360, 1080))
        self.a_widget_2.setStyleSheet("background-color: rgb(40, 48, 70);")
        self.a_widget_2.setObjectName("a_widget_2")
        self.a_widget_1 = QtWidgets.QWidget(self.a_widget_2)
        self.a_widget_1.setGeometry(QtCore.QRect(0, 0, 360, 45))
        self.a_widget_1.setStyleSheet("background-color: rgb(22, 29, 49);")
        self.a_widget_1.setObjectName("a_widget_1")
        self.a_txtlbl_title = QtWidgets.QLabel(self.a_widget_1)
        self.a_txtlbl_title.setGeometry(QtCore.QRect(20, 12, 153, 24))
        self.a_txtlbl_title.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(62)
        self.a_txtlbl_title.setFont(font)
        self.a_txtlbl_title.setStyleSheet("font-family: Roboto;\n"
"font-style: normal;\n"
"font-weight: 500;\n"
"font-size: 15px;\n"
"color: #D0D2D6;")
        self.a_txtlbl_title.setObjectName("a_txtlbl_title")
        self.a_btn_exit = QtWidgets.QPushButton(self.a_widget_1)
        self.a_btn_exit.setGeometry(QtCore.QRect(319, 13, 20, 20))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(14)
        self.a_btn_exit.setFont(font)
        self.a_btn_exit.setStyleSheet("color: rgb(208, 210, 214);")
        self.a_btn_exit.setObjectName("a_btn_exit")
        self.formLayoutWidget = QtWidgets.QWidget(self.a_widget_2)
        self.formLayoutWidget.setGeometry(QtCore.QRect(10, 50, 341, 231))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 23, 0, 5)
        self.formLayout.setObjectName("formLayout")
        self.a_lbl_name = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.a_lbl_name.setFont(font)
        self.a_lbl_name.setStyleSheet("font: 12pt \"Roboto\";\n"
"color: #B4B7BD;")
        self.a_lbl_name.setObjectName("a_lbl_name")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.a_lbl_name)
        self.a_lineEdit_name = QtWidgets.QLineEdit(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.a_lineEdit_name.setFont(font)
        self.a_lineEdit_name.setStyleSheet("QLineEdit {\n"
"background-color: #283046;\n"
"border: 1px solid rgb(122, 122, 122);\n"
"border-radius: 5px;\n"
"font: 12pt \"Roboto\";\n"
"color: rgb(255, 255, 255);\n"
"transition-duration: 0.4s;\n"
"}\n"
"QLineEdit:hover {\n"
"    background-color: rgb(40, 48, 70); \n"
"    color: rgb(255, 255, 255);\n"
"    border: 2px solid rgb(95, 85, 200);\n"
"    border-radius: 5px;\n"
"}")
        self.a_lineEdit_name.setObjectName("a_lineEdit_name")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.a_lineEdit_name)
        self.a_lbl_category = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(12)
        self.a_lbl_category.setFont(font)
        self.a_lbl_category.setStyleSheet("color: rgb(185, 185, 195);")
        self.a_lbl_category.setObjectName("a_lbl_category")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.a_lbl_category)
        self.a_comboBox = QtWidgets.QComboBox(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.a_comboBox.setFont(font)
        self.a_comboBox.setStyleSheet("QComboBox {\n"
"background-color: #283046;\n"
"border: 1px solid rgb(122, 122, 122);\n"
"border-radius: 5px;\n"
"font: 12pt \"Roboto\";\n"
"color: rgb(255, 255, 255);\n"
"transition-duration: 0.4s;\n"
"}\n"
"QComboBox:hover {\n"
"    background-color: rgb(40, 48, 70); \n"
"    color: rgb(255, 255, 255);\n"
"    border: 2px solid rgb(95, 85, 200);\n"
"    border-radius: 5px;\n"
"}")
        self.a_comboBox.setObjectName("a_comboBox")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.a_comboBox)
        self.a_lbl_time = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(12)
        self.a_lbl_time.setFont(font)
        self.a_lbl_time.setStyleSheet("color: rgb(185, 185, 195);")
        self.a_lbl_time.setObjectName("a_lbl_time")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.a_lbl_time)
        self.a_lineEdit_time = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.a_lineEdit_time.setStyleSheet("QLineEdit {\n"
"background-color: #283046;\n"
"border: 1px solid rgb(122, 122, 122);\n"
"border-radius: 5px;\n"
"font: 12pt \"Roboto\";\n"
"color: rgb(255, 255, 255);\n"
"transition-duration: 0.4s;\n"
"}\n"
"QLineEdit:hover {\n"
"    background-color: rgb(40, 48, 70); \n"
"    color: rgb(255, 255, 255);\n"
"    border: 2px solid rgb(95, 85, 200);\n"
"    border-radius: 5px;\n"
"}")
        self.a_lineEdit_time.setObjectName("a_lineEdit_time")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.a_lineEdit_time)
        self.a_lbl_fdate = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(12)
        self.a_lbl_fdate.setFont(font)
        self.a_lbl_fdate.setStyleSheet("color: rgb(185, 185, 195);")
        self.a_lbl_fdate.setObjectName("a_lbl_fdate")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.a_lbl_fdate)
        self.a_dateEdit = QtWidgets.QDateEdit(self.formLayoutWidget)
        self.a_dateEdit.setStyleSheet("QDateEdit {\n"
"background-color: #283046;\n"
"border: 1px solid rgb(122, 122, 122);\n"
"border-radius: 5px;\n"
"    font: 12pt \"Roboto\";\n"
"color: rgb(255, 255, 255);\n"
"transition-duration: 0.4s;\n"
"}\n"
"QDateEdit:hover {\n"
"    background-color: rgb(40, 48, 70); \n"
"    color: rgb(255, 255, 255);\n"
"    border: 2px solid rgb(95, 85, 200);\n"
"    border-radius: 5px;\n"
"}")
        self.a_dateEdit.setObjectName("a_dateEdit")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.a_dateEdit)
        self.a_lbl_comment = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(12)
        self.a_lbl_comment.setFont(font)
        self.a_lbl_comment.setStyleSheet("color: rgb(185, 185, 195);")
        self.a_lbl_comment.setObjectName("a_lbl_comment")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.a_lbl_comment)
        self.a_te_comment = QtWidgets.QPlainTextEdit(self.formLayoutWidget)
        self.a_te_comment.setMaximumSize(QtCore.QSize(316, 126))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.a_te_comment.setFont(font)
        self.a_te_comment.setStyleSheet("QPlainTextEdit {\n"
"background-color: #283046;\n"
"border: 1px solid rgb(122, 122, 122);\n"
"border-radius: 5px;\n"
"font: 12pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);\n"
"transition-duration: 0.4s;\n"
"}\n"
"QPlainTextEdit:hover {\n"
"    background-color: rgb(40, 48, 70); \n"
"    color: rgb(255, 255, 255);\n"
"    border: 2px solid rgb(95, 85, 200);\n"
"    border-radius: 5px;\n"
"}")
        self.a_te_comment.setObjectName("a_te_comment")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.a_te_comment)
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.a_widget_2)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 280, 341, 91))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 149, 0)
        self.horizontalLayout.setSpacing(10)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.a_btn_save = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.a_btn_save.setMaximumSize(QtCore.QSize(102, 37))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(62)
        self.a_btn_save.setFont(font)
        self.a_btn_save.setStyleSheet("QPushButton {\n"
"background-color: #7367F0;\n"
"border-radius: 5px;\n"
"font-family: Roboto;\n"
"font-style: normal;\n"
"font-weight: 500;\n"
"font-size: 14px;\n"
"line-height: 17px;\n"
"text-align: center;\n"
"letter-spacing: 0.4px;\n"
"color: #FFFFFF;\n"
"transition-duration: 0.4s;\n"
"}\n"
"QPushButton:hover {\n"
"  background-color: rgb(40, 48, 70); \n"
"  color: rgb(115, 103, 240);\n"
"  border: 2px solid rgb(95, 85, 200);\n"
"}")
        self.a_btn_save.setObjectName("a_btn_save")
        self.horizontalLayout.addWidget(self.a_btn_save)
        self.a_btn_del = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.a_btn_del.setMaximumSize(QtCore.QSize(102, 37))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(62)
        self.a_btn_del.setFont(font)
        self.a_btn_del.setStyleSheet("QPushButton {\n"
"background-color: rgb(40, 48, 70); \n"
"border-radius: 5px;\n"
"border: 2px solid rgb(234, 84, 85);\n"
"font-family: Roboto;\n"
"font-style: normal;\n"
"font-weight: 500;\n"
"font-size: 14px;\n"
"line-height: 17px;\n"
"text-align: center;\n"
"letter-spacing: 0.4px;\n"
"color: rgb(234, 84, 85);\n"
"transition-duration: 0.4s;\n"
"}\n"
"QPushButton:hover {\n"
"background-color: rgb(234, 84, 85);\n"
"color: rgb(255, 255, 255);\n"
"border: 2px solid rgb(234, 84, 85);\n"
"}")
        self.a_btn_del.setObjectName("a_btn_del")
        self.horizontalLayout.addWidget(self.a_btn_del)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Добавить событие"))
        self.a_txtlbl_title.setText(_translate("Form", "Добавить событие"))
        self.a_btn_exit.setText(_translate("Form", "X"))
        self.a_lbl_name.setText(_translate("Form", "Название"))
        self.a_lbl_category.setText(_translate("Form", "Категория"))
        self.a_lbl_time.setText(_translate("Form", "Потратил времени"))
        self.a_lbl_fdate.setText(_translate("Form", "Дата"))
        self.a_lbl_comment.setText(_translate("Form", "Комментарий"))
        self.a_btn_save.setText(_translate("Form", "Применить"))
        self.a_btn_del.setText(_translate("Form", "Отмена"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
